### ISSUE TITLE
파래님 저에요 ㅠㅠ

### ISSUE THREAD

**Issue by PartAy001** [FarAway6834/FarAway6834.github.io#1]
저에요 Part A ㅠㅠ
냥쿠님좀 불러쥬ㅓ요 ㅠㅠ

**Comment by PartAy001** [comment]
저 그때 옾접당한거 기억하낭

**Comment by PartAy001** [comment]
저 그때 옾접당한거 기억하나요? Karlit 프로그래밍 방에서?

**Comment by PartAy001** [comment]
[이 톡](https://github.com/PartAy001/TALK2)에서 대화해요 ㅠㅠ
냥쿠님 [이 톡](https://github.com/PartAy001/TALK)으로 대화 부탁드리고요 ㅠㅠ

**Comment by PartAy001** [comment]
태산크루 들어가는거 대리 가능하신가요? ㅠㅠ

**Comment by PartAy001** [comment]
저 기억나시죠? ㅠㅠ 기억하시죠? ㅠㅠ

**Comment by PartAy001** [comment]
> [이 톡](https://github.com/PartAy001/TALK2)에서 대화해요 ㅠㅠ
> 냥쿠님 [이 톡](https://github.com/PartAy001/TALK)으로 대화 부탁드리고요 ㅠㅠ

(냥쿠님 계정 옶으면... 어카징? ㅠㅠ)

**Comment by FarAway6834** [comment]
오오오, PartA님 ㅠㅠ 얼마만인가요..., 당연히 도와드리죠 ㅎ (찡긋)
